# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This software may be used and distributed in accordance with
# the terms of the DINOv3 License Agreement.
#
# Written as an extension of DINOv3 (https://github.com/facebookresearch/dinov3).

"""Permutation classification: which of 1000 fixed permutations shuffled the mosaic.

After Noroozi & Favaro (arXiv:1603.09246). The cut and mosaic are the same as relpos; only
the target differs. Sets are generated by their greedy maximal-Hamming procedure and stored,
so a class index means the same thing across runs.
"""

import itertools
import os

import numpy as np
import torch
from torch import Tensor, nn
from torch.nn.init import trunc_normal_

PERM_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "permutations")


def generate_permutations(n_tiles: int, n: int = 1000, seed: int = 0, pool: int = 100_000) -> np.ndarray:
    """Greedy maximal-Hamming permutation set.

    Enumerates all orderings when that is feasible (9 tiles), otherwise draws a random
    candidate pool: with 16 or 144 tiles two random orderings already differ almost everywhere.
    """
    rng = np.random.default_rng(seed)
    if n_tiles <= 9:
        cand = np.array(list(itertools.permutations(range(n_tiles))), dtype=np.int16)
    else:
        cand = np.unique(np.argsort(rng.random((pool, n_tiles)), axis=1).astype(np.int16), axis=0)
    chosen = np.zeros(len(cand), bool)
    score = np.zeros(len(cand), np.int64)
    j = int(rng.integers(len(cand)))
    out = []
    for _ in range(n):
        out.append(cand[j])
        chosen[j] = True
        score += (cand != cand[j]).sum(1)
        j = int(np.where(chosen, -1, score).argmax())
    return np.stack(out).astype(np.int16)


def load_permutations(grid: int) -> Tensor:
    f = os.path.join(PERM_DIR, f"permutations_1000_g{grid}.npy")
    if not os.path.exists(f):
        os.makedirs(PERM_DIR, exist_ok=True)
        np.save(f, generate_permutations(grid * grid))
    return torch.from_numpy(np.load(f).astype(np.int64))


class PermutationHead(nn.Module):
    """Per-slot projection, then a classifier over the slots concatenated in slot order.

    The per-slot width is set so the concatenation has the same size at any grid, keeping
    head capacity comparable across grids.
    """

    def __init__(self, embed_dim: int, n_tiles: int, n_perms: int = 1000,
                 concat_dim: int = 4608, fc7_dim: int = 4096):
        super().__init__()
        assert concat_dim % n_tiles == 0
        self.n_tiles = n_tiles
        self.fc6 = nn.Sequential(nn.Linear(embed_dim, concat_dim // n_tiles), nn.ReLU(inplace=True))
        self.fc7 = nn.Sequential(nn.Linear(concat_dim, fc7_dim), nn.ReLU(inplace=True))
        self.fc8 = nn.Linear(fc7_dim, n_perms)

    def init_weights(self):
        self.apply(_init_linear)

    def forward(self, slots: Tensor) -> Tensor:
        x = self.fc6(slots)
        x = x.unflatten(0, (-1, self.n_tiles)).flatten(1)
        return self.fc8(self.fc7(x))


def _init_linear(m):
    if isinstance(m, nn.Linear):
        trunc_normal_(m.weight, std=0.02)
        if m.bias is not None:
            nn.init.constant_(m.bias, 0)


class PermutationLoss(nn.Module):
    """Cross-entropy over the permutation classes."""

    def forward(self, logits: Tensor, label: Tensor) -> Tensor:
        return nn.functional.cross_entropy(logits.float(), label)

    @staticmethod
    @torch.no_grad()
    def accuracy(logits: Tensor, label: Tensor) -> Tensor:
        return (logits.argmax(-1) == label).float().mean()
